# Generated by Django 4.1.1 on 2022-09-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_images_alter_location_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
