# Generated by Django 4.1.1 on 2022-10-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_location_latitude_location_longtitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['title']},
        ),
    ]
