# Generated by Django 4.1.1 on 2022-10-07 07:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_alter_location_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
