# Generated by Django 4.1.1 on 2022-10-07 07:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_images_image_image_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткое описание'),
        ),
    ]
